name: Build Devcontainer

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .devcontainer
        file: .devcontainer/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/devcontainer:latest
        platforms: linux/amd64, linux/arm64

    - name: Verify Image
      run: docker run --rm ghcr.io/${{ github.repository }}/devcontainer:latest
